### ISSUE TITLE
Push v1.4.4 to maven central

### ISSUE THREAD

**Issue by asanthan-amazon** [cojen/Tupl#112]
Hi,
Please release latest version v1.4.4 to maven central.

Current maven central has v1.3 which does not have support for union,intersection and bugfixes.

**Comment by broneill** [comment]
I never got the Maven Central thing to work. Someone else had published it the past, and I never got around to publishing it again. Keep in mind that the license changed with version 1.4 to AGPLv3, which might be an issue if you're already using version 1.3.

**Comment by asanthan-amazon** [comment]
Thanks for mentioning about license. :)
