### ISSUE TITLE
Flexible support for non-byte[] keys and values in Tupl View

### ISSUE THREAD

**Issue by avshabanov** [cojen/Tupl#58]
# The Problem

Right now tupl supports only byte arrays as keys and values assuming tupl clients to convert keys and values to byte arrays prior to write operations in tupl and convert back from byte[] to objects in read operations. This introduces an overhead (albeit not a big one) as write and read operations are leaving byte arrays to be reclaimed by GC.

# Feature Proposal

In order to minimize the number of created byte arrays Tupl may support additional set of methods that may take an interface supporting (de)serialization of passed keys and values to/from binary streams thus reducing GC overhead.

This support may look as follows:

In View.java
```java
package org.cojen.tupl;

import org.cojen.tupl.io.Mapper; // new entity

public interface View {
  // new methods:
  <K, V, M extends Mapper<K, V>> void store(Transaction txn, M mapper, K key, V value) throws IOException;
  <K, V, M extends Mapper<K, V>> V load(Transaction txn, M mapper, K key) throws IOException;
  

  // old methods for compatibility:
  default void store(Transaction txn, byte[] key, byte[] value) throws IOException {
    store(txn, ByteArrayMapper.INSTANCE, key, value);
  }

  default void load(Transaction txn, byte[] key) throws IOException {
    return load(txn, ByteArrayMapper.INSTANCE, key);
  }
}
```

Mapper.java:
```java
package org.cojen.tupl.io;

public interface Mapper<K, V> {
  void writeKeyTo(K key, OutputStream stream) throws IOException;
  K readKeyFrom(InputStream stream, int size) throws IOException;

  void writeValueTo(V value, OutputStream stream) throws IOException;
  V readValueFrom(InputStream stream, int size) throws IOException;
}
```

ByteArrayMapper.java:
```java
public final class ByteArrayMapper implements Mapper<byte[], byte[]> {
  public ByteArrayMapper INSTANCE = new ByteArrayMapper();

  private ByteArrayMapper() {}

  @Override
  public void writeKeyTo(byte[] key, OutputStream stream) throws IOException {
    stream.write(key);
  }

  @Override
  public byte[] readKeyFrom(InputStream stream, int size) throws IOException {
    return readAllBytes(stream, size);
  }

  @Override
  public void writeValueTo(byte[] value, OutputStream stream) throws IOException {
    stream.write(value);
  }

  @Override
  public byte[] readValueFrom(InputStream stream, int size) throws IOException {
    return readAllBytes(stream, size);
  }

  private static byte[] readAllBytes(InputStream stream, int size) throws IOException {
    final byte[] result = new byte[size];
    for (int offset = 0; offset < size;) {
      int bytesRead = stream.read(result, offset, size - offset);
      if (bytesRead < 0) {
        break;
      }
      offset += bytesRead;
    }
    return result;
  }
}
```

**Comment by avshabanov** [comment]
I am not sure however if introducing such feature would have beneficial effect to the GC - at least probably not for load operations - as far as I can see Tupl operates with byte[] in load operations, however write operations seem to use stream-alike interface for writing values - e.g. RedoWriter.writeBytes

**Comment by broneill** [comment]
The risk to exposing more direct control over accessing keys and values is internal deadlocks and database corruption. Passing streams to the Mapper can offer some safety, but it would mean that an object still gets allocated. The implementation would be tricky, especially for store operations. The key and value would need to be fully buffered first, to determine what the length is. This of course means more allocations, and possible extra copies to handle buffer growth.

I do want to support stream access for values, but the intent is for supporting very large values (gigabytes) and not for reducing GC overhead.

**Comment by avshabanov** [comment]
If serialized size is the only issue and it should be known in advance, then it shouldn't be a problem, esp. if Thrift or protobuf are used - e.g. serialized size might be retrieved before serializing object to InputStream, protobuf Message interface supports getSerializedSize that can be called to get the size in bytes of the serialized object representation. Again, I believe the same is true for Thrift and this also can be relatively easily implemented for primitive types, such as ints.

**Comment by avshabanov** [comment]
On second thought I think it's a terrible idea. I don't think it'd yield any performance benefits. And large values probably can be best stored physically separated into chunks / or in separate storage (e.g. S3).
