### ISSUE TITLE
Fail on commit instead of modification time?

### ISSUE THREAD

**Issue by amcp** [cojen/Tupl#65]
Suppose I have two transactions, tx1 and tx2.
In both tx1 and in tx2, I change the same key in the same index. First I change the key in tx1 and then I change the key in tx2.
Using LockMode.UPGRADABLE_READ, the write to this key in tx2 fails with a LockFailureException. This is behavior I expect, so this issue is just a question.

Is there a configuration that would allow me to fail tx2 on commit() time, and not mutation time?
Is there a code change I could make to allow me to fail tx2 in close proximity to its commit() call?

**Comment by broneill** [comment]
If you change the key in txn2, it should block waiting to acquire the lock. It will fail only when it times out. Neither transaction should fail in practice, unless the transaction is open too long or the lock timeout is too short.
