### ISSUE TITLE
Backwards compatibility for persistence format?

### ISSUE THREAD

**Issue by MartinHaeusler** [cojen/Tupl#68]
Hello,

me and my team are happy users of TUPL `1.3.11`. We would like to upgrade to the latest version of the library. Since we use it in production, there are existing instances of our data on TUPL `1.3.11` out there. Is it safe to upgrade our TUPL versoin to the latest one, i.e. have there been any breaking changes in the persistence format, or are there any other compatibility issues? I checked the changelog, I just wanted to ask if there are any known issues and/or incompatibilities.

Thanks for your awesome library!

Martin

**Comment by broneill** [comment]
It should be fine to upgrade. The versioning scheme permits breaking changes only when the first or second digit of the version number changes. This is explained in the [versioning](https://github.com/cojen/Tupl/blob/master/VERSIONING.md) file.

**Comment by MartinHaeusler** [comment]
Excellent, thanks for the fast response.
